canopas/canopas-blog-admin

lib/post.js, pages/author/[slug].js, pages/categories/[slug].js, pages/post/[slug].js, pages/tags/[slug].js
=> Get blog by category

component/comment/commentForm.js, component/comment/comments.js, pages/author/[slug].js, pages/categories/[slug].js, pages/index.js, pages/tags/[slug].js
- Implement thread comments on blog post
- Show the total comments in author, category, and tag page
=> Thread comments

pages/author/[slug].js, pages/categories/[slug].js, pages/index.js, pages/post/[slug].js, pages/tags/[slug].js
After build the `page navigator` is not working. so,
Use `Link component` : https://nextjs.org/learn/basics/navigate-between-pages/client-side
=> Use link component for the navigate pages

components/partials/header.js, pages/index.js, pages/post/[slug].js, yarn.lock
[Screencast from 13-01-23 04:53:22 PM IST.webm](https://user-images.githubusercontent.com/94360312/212309682-03d78927-02b5-4fdf-a9aa-099f9fd4434e.webm)
=> Feat : design all blog section ui

components/partials/header.js, pages/_app.js, pages/index.js, pages/post/[slug].js, pages/seo.js, utils.js
**I have minor change on header.js, becoz i was see error on header and get solution this error ,so i have sloved this error.**
=> add meta properties

.github/pull_request_template.md, assets/css/global.css, components/partials/header.js, components/posts/postsList.js, components/posts/recommandedPosts.js, package.json, pages/[slug].js, pages/index.js, yarn.lock
**Tested on:**
**Description :**
- added some changes make website blog better view in safari browser.
- **Fixed the problem**
1. Safari browser was creating a blog image animation issue when a user clicked on a recommended blog..
2. Safari browser was create smooth scroll content problem.
3. In Safari browser, blocks code did not provide side scrolling option, it wrapped the overflow content.
4. In the iPhone, content images did not look good.
=> fix : some fixes in real devices

.github/pull_request_template.md
=> Docs: update PR template

components/partials/header.js, config.js, pages/index.js
-  redesign header same as [canopas.com ](https://canopas.com/) & also changes routes
-  add condition in category section , if category not exist than hide category section.
=> style : some ui changes & routes

components/posts/postsList.js, pages/index.js
https://user-images.githubusercontent.com/115449373/234209642-085e24ad-b679-4a85-89dd-46537291be47.mp4
https://user-images.githubusercontent.com/115449373/234209270-b9bc1aa5-d833-4a81-b075-627705473c04.mp4
**Design should be tested on:** 
- add infinte scroll for more than 10 blogs in canopas blogs
- in post list( all blog ,featured bloglist and bloglist by tag name) add infinte scroll.
- In both these videos I have used 3 blogs per page just for recording, so you can understand better.
=> Feat : add infinte scroll for post

components/partials/header.js, next.config.js, pages/[slug].js
- added some route using hamburger menu in header , and fixed basepath issue eg . when user click another pages(portfoilo) that time open {url}/resources/portfolio instead of {url}/portfolio, i fixed it.
=> Perf: add some routes & change basePath

components/partials/header.js, config.js, next.config.js, pages/[slug].js
=> Fix: header redirection

components/partials/header.js
=> Add resources header

components/posts/postsList.js, pages/[slug].js, utils.js
**Design should be tested on:**  - **not applicable**
- changed tag data ,because in backend strapi admin panel (changes tags data objects).
=> fix : tag data issue

config-prod.js, pages/[slug].js, pages/_app.js, pages/index.js, utils.js
=> Feat: show draft posts in dev

.github/workflows/deploy-dev.yml
- Added new workflow for the dev environment
- It will create branch development, merge branch changes into it and push it to the origin
- When changes are merged to development, AWS amplify workflow will be triggered and deploy current branch changes to development
=> Create dev workflow

.github/workflows/deploy-dev.yml, components/partials/header.js, config-prod.js, config.js
=> Change page title

.github/workflows/deploy-dev.yml, pages/[slug].js
=> Fix dev deployment

package.json, pages/[slug].js, yarn.lock
https://www.awesomescreenshot.com/video/17123711?key=472e8b01c7c6a8322ff981be49692208
- add share blog functionality in canopas blog.
- Share blog  on Facebook,linkedIn,twitter,reddit.
- add copy linkButton for copy blog url.
=> feat: add share link's for share blog & add copy linkButton for copy blog url

components/partials/header.js
- redesign button style and change button place in hamburger menu.
=> Fix : changes design in header hamburger

.github/workflows/deploy-dev.yml, pages/[slug].js
- this change used for when user open canopas blog in mobile that time used web share api for sharing blog.
=> feat : add mobile sharing functionality for mobile

components/partials/header.js, components/posts/recommandedPosts.js, config-prod.js, config.js, pages/[slug].js, pages/featured/index.js, pages/index.js, pages/tag/[slug].js, tailwind.config.js
https://github.com/canopas/canopas-blog/assets/115449373/02349b75-e37a-4fae-ad82-886227ad123b
**Design should be tested on:** **- not applicable**
- UI changes : recommanded blogs section placed change from below indexcontent to right side.
=> Style : changes place of recommanded blog section

components/comments/commentForm.js, components/comments/index.js, config-prod.js, config.js, pages/[slug].js, pages/featured/index.js, pages/index.js, utils.js
https://github.com/canopas/canopas-blog/assets/115449373/1d4ca870-e7f3-418c-8cd2-f1f81c430296
**Design should be tested on:** - **testing for image loading problem**
- added subscription functionality for user. it provide to subscribe or unsubscribe for users.
- and fixed some image loading problem in first time loading and hard refresh. 
- And I also added the name field and removed the username field in the user table, so I changed some code in the comment section e.g. When the user adds their name it returns the user id and creates a comment if the name already exists at that time, but when the user adds a name and that name does not exist then update …
=> feat : add subscription functionality

pages/[slug].js, utils.js
**Design should be tested on:** - not applicable
- when some data in blog not exist that time show error msg in frontend , so i have fixed that.
=> fix : validation issues

config-prod.js
=> Enhance: Update SEO

components/posts/postsList.js, components/posts/recommandedPosts.js, pages/[slug].js, pages/index.js
- Issue : author image looked very bad , so i fixed that.
=> fix : author image break issue

pages/_app.js
- remove roborts meta from _app.js for performance improvment
=> perf : remove robots meta from _app.js

package.json, pages/[slug].js, pages/index.js, yarn.lock
Description:
- Add cache-control header
- Lazy load images
- Remove unused dependencies
=> Improve page speed

assets/css/global.css, assets/images/footer/new-bg.svg, components/cta/CTA2.js, components/partials/footer.js, components/partials/header.js, components/posts/recommandedPosts.js, config-prod.js, config.js, pages/[slug].js, pages/_app.js
- added footer section in canopas blog.
**fix some issue :** 
1. fix header scrolling issue.
2. add some top space in index content and also content scrolling.
3. remove some class in  recommand section.
4. remove first heading<h1,h2> top margin in blog content.
5. and also set proper second CTA with footer , because it designed before footer and when i set CTA design with footer that time it not looked proper , i have fixed it. **- second video**
https://github.com/canopas/canopas-blog/assets/115449373/f30329cb-341b-4668-9e60-b3158cad074e
https://github.com/canopas/canopas-blog/assets/115449373/c9d2f158-9ae2-448d-b9aa-c17c …
=> feat : add footer section

components/partials/header.js, config-prod.js, config.js, tailwind.config.js
**Design Video:**
https://github.com/canopas/canopas-blog/assets/85920585/f0a0138a-b89d-4df1-8c5f-518ac7ee44fa
=> Add contribution menu in header

components/partials/footer.js, pages/[slug].js
**Description :**
- added logic to get CTA section , which CTA include in post data.
- also i fogot to add copyright icon and year in footer , so i have added.
=> feat : add cta in post page

components/cta/CTA1.js, components/partials/header.js, package.json, pages/[slug].js, pages/index.js, pages/seo.js, yarn.lock
- removed cache from [slug].js & index.js
- removed all name except of post title in seo post title.
- fixed contribution page link problem in header.
- fixed 500 - internal server error(swiper) in CTA 1.
=> fix : some fixes in seo and header

components/partials/header.js, config-prod.js, config.js
- remove contribution in feature flag and deploy in live
=> refactor :Remove feature flag to deploy on live

components/cta/api.js
- added some changes in this brance becuase in above(fix-cta-section-issues) brance not merge this changes.
=> fix : change localstorage client-name position

components/comments/index.js, components/cta/CTA2.js, components/cta/CTA3.js, components/cta/api.js, components/posts/recommandedPosts.js, pages/[slug].js, pages/featured/index.js, pages/index.js, pages/resources.js, pages/tag/[slug].js, utils.js
- added related posts feature : related posts display by their category and tags.
=> feat : add related post feature

assets/css/global.css, components/cta/CTA5.js, components/partials/footer.js, components/partials/header.js, pages/[slug].js, pages/index.js, tailwind.config.js
- make CTA , Footer and Header content unclickable.
- increased some width of canopas icon in index page , beacuse that image was cut on right and left side.
- changed button position in mobile device (CTA 5)
=> refactor : make some content unclickable in CTA ,Footer and Header

components/cta/CTA1.js, config-prod.js, config.js, package.json, pages/[slug].js, pages/index.js, pages/resources.js, tailwind.config.js, utils.js, yarn.lock
- upadte all dependencies.
- fix some warning when we run yarn build.
- fix search post UI.
- and tested search and filter functionality in the index.js page. That search post functionality was giving an error because we changed the tag functionality in the backend so the search functionality couldn't get the tag data correctly, so I fixed that.
- fixed tag UI design image-1 to image 2
- make recommanded blog feature live.
**issue** - image-1
**fixed** - image-2
=> build : update dependencies and fix warning

admin/src/api/post/content-types/post/lifecycles.js, pages/[slug].js
- result.title and result.tag are used without checking if the result data exists then run the function, so that gave server error on published data, I fixed it.
- with change variable for remove first Heading margin in blog content.
=> fix : server error in strapi

admin/src/api/post/content-types/post/schema.json, components/comments/index.js, components/cta/CTA3.js, components/partials/footer.js, components/partials/header.js, components/posts/recommandedPosts.js, pages/[slug].js, pages/_app.js, pages/_document.js, pages/featured/index.js, pages/index.js, pages/resources.js, pages/seo.js, pages/tag/[slug].js, pages/unsubscribe/index.js, utils.js
- add keyword field in post table - strapi
- import all components using dynamic
- resolve some lighthouse error
- redesign recommanded section for desktop
- fix some issue
- change seo
- Some lighthouse error I can't resolve, because it is related to the strapi admin panel data. so that performance score down.
**index.js**
- **desktop**
- **mobile**
=> perf : improve performance and pagespeed

README.md, admin/src/api/post/content-types/post/lifecycles.js, admin/src/extensions/users-permissions/content-types/user/schema.json, admin/src/extensions/users-permissions/strapi-server.js, components/partials/footer.js, components/partials/header.js
- fixed published date issue
- fixed user table issue that generated by username
- fixed subscribe user issue : that create password issue.
- set contribution(underline on hover) same as canopas website header
- fix footer icon position
=> fix : some issues in strapi & frontend

admin/config/plugins.js, admin/package.json, admin/src/extensions/users-permissions/content-types/user/schema.json, admin/yarn.lock
- added system that send error notification mail to me in strapi.
- added required in password and role inside users table.
=> feat : error notification system in strapi

README.md, admin/config/plugins.js, admin/package.json, admin/yarn.lock, pages/[slug].js
**Description :**
- add scheduled date and time for publish blog in strapi.
- also added condition in author details section that without author bio section don't display.
=> feat : add scheduler for publish blog

pages/seo.js
=> Fix syntax error in json-ld

assets/css/global.css, components/authorDetails.js, components/comments/commentForm.js, components/cta/CTA1.js, components/cta/CTA2.js, components/cta/CTA3.js, components/cta/CTA4.js, components/cta/CTA5.js, components/partials/footer.js, components/partials/header.js, components/posts/postsList.js, components/posts/recommandedPosts.js, package.json, pages/[slug].js, pages/_app.js, pages/featured/index.js, pages/index.js, pages/resources.js, pages/tag/[slug].js, tailwind.config.js, yarn.lock
**Descriprtion**
- fixed font loading issue.
- issue : When we first open the canopas blog the font changes for a while throughout the website and then the correct fonts are displayed, so I fixed that.
- for your checking open : [dev-stack-website](https://dev-stack.canopas.com/resources)
=> fix: font loading problem

website/assets/css/global.css
**Description** :
change h1 heading font size same as h2 , and now h1 and h2 font size same , once sir change all font h2 to h1 , then i will change that.
=> style: change heading font size

.github/workflows/deploy-prod.yml
=> Fix: move config.prod to config

.github/workflows/deploy-prod.yml
=> Fix: prod workflow

admin/Dockerfile
=> fix : deploy error

admin/src/api/author/content-types/author/schema.json, admin/src/api/post/content-types/post/lifecycles.js, website/config.js
**Description :**
- fix some issue in blog content and also increase max value of author bio in author table.
=> fix : change content value in config

admin/config/database.js, admin/docker-compose.yaml, admin/package.json, admin/yarn.lock, website/components/authorDetails.js, website/utils.js, website/yarn.lock
=> Connect db to rds

README.md, admin/public/emailTemplates/comment.html, admin/public/emailTemplates/subscribe.html
=> Fix: subscribe links in admin panel

.github/workflows/admin.yml, admin/deploy.sh, admin/nginx/conf.d/website-blog.conf, admin/package.json, admin/yarn.lock
=> Deploy: website with ssl certs

admin/config/plugins.js
=> Fix: link preview iframe

admin/src/api/post/content-types/post/lifecycles.js
=> Update: slug for posts

admin/src/api/post/content-types/post/lifecycles.js
=> Fix: published dates

.github/workflows/admin.yml, README.md, admin/public/emailTemplates/subscribe.html, admin/src/api/cta/content-types/cta/schema.json, admin/src/api/post/content-types/post/lifecycles.js, admin/src/api/post/content-types/post/schema.json, admin/src/plugins/guidelines/admin/src/pages/guidelines.md
=> Feat : Updated Guidelines

admin/config/plugins.js
=> Update: Increase file size limit for media library

admin/nginx/conf.d/website-blog.conf
=> Update: file upload size limit on nginx

.gitignore, admin/Dockerfile, admin/src/api/post/content-types/post/lifecycles.js
=> Fix: puppeteer issue

admin/src/api/post/content-types/post/lifecycles.js
=> Fix previews

admin/src/api/post/controllers/post.js, admin/yarn.lock
- Added recommended blogs fetch directly with the post data
- Added readTime field.
=> Admin: improve api performance

admin/config/middlewares.js, admin/src/api/post/controllers/post.js
=> Enable text compression in response

admin/src/api/post/content-types/post/lifecycles.js
=> Fix reading time logic

admin/src/api/post/controllers/post.js, admin/src/api/post/routes/custom.js
=> Add paginate api

admin/src/api/post/controllers/post.js
=> Fix: posts api query pagination

admin/package.json, admin/src/api/post/content-types/post/schema.json, admin/src/api/tag/controllers/tag.js, admin/src/api/tag/routes/custom.js, admin/yarn.lock
=> Upgrade: tagsInput plugin

admin/src/api/post/content-types/post/lifecycles.js
=> Fix url preview

admin/package.json, admin/yarn.lock
- Downgrade all the dependencies causes some issues in live
=> Downgrade all the dependencies

admin/src/api/post/content-types/post/lifecycles.js
- Commented code of sending an email when publishing the blog/resource
=> Stop sending mails on publish the post
